# Generated by Django 6.0.5 on 2026-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['platform', 'account_name']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='postplatform',
            name='published_post_id',
            field=models.CharField(blank=True, help_text='ID returned by platform after successful publish', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_id',
            field=models.CharField(blank=True, help_text='Platform user/page/business ID', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_name',
            field=models.CharField(blank=True, help_text='e.g. @handle or Page name', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='app_id',
            field=models.CharField(blank=True, help_text='Meta App ID', max_length=100),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='app_secret',
            field=models.CharField(blank=True, help_text='Meta App Secret — keep private', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='ig_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID', max_length=100),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID (required for Instagram Business)', max_length=100),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='permissions_granted',
            field=models.TextField(blank=True, help_text='Comma-separated list of approved permissions'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('disconnected', 'Disconnected')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(help_text='User or Page access token'),
        ),
    ]
