# Generated by Django 5.2.14 on 2026-05-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_social_account_fields'),
        ('publisher', '0002_webhookevent'),
    ]

    operations = [
    ]
